export const GET_MEME_REQUEST = "GET_MEME_REQUEST";
export const GET_MEME_RESPONSE = "GET_MEME_RESPONSE";
export const CREATE_MEME_REQUEST = "CREATE_MEME_REQUEST";
export const CREATE_MEME_RESPONSE = "CREATE_MEME_RESPONSE";
export const DEFAULT = "DEFAULT";
